project:
  type: website
  output-dir: docs

website:
  title: "Create an NPM Package"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: introduction/index.qmd
      - text: "Requirements"
        file: requirements/index.qmd 
      - text: "Building Our Application"
        file: building-our-application/index.qmd
      - text: "Conclusion"
        file: conclusion/index.qmd        

sidebar:
  - title: "Introduction"
    style: "docked"
    background: light
    contents:
      - introduction/index.qmd
  - title: "Requirements"
    style: "docked"
    background: light
    contents:
      - requirements/index.qmd
  - title: "Building Our Application"
    style: "docked"
    background: light
    contents:
      - building-our-application/index.qmd
  - title: "Conclusion"
    style: "docked"
    background: light
    contents:
      - conclusion/index.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
