---
title: "Creating a GitHub Action"
---

Based on "Fully Automated npm publish using GitHub Actions and Semantic Release" at https://www.youtube.com/watch?v=QZdY4XYbqLI

The next step is to create a GitHub action so click the "**Actions**" tab on the GitHub repository page of **foo-component**. From the **Continuous Integration** workflows choose the workflow called **NodeJS: Build and test a Node.js project with npm.** and click on "**configure**".

Stick with the default name that is given to the Yaml file, here: **node.js.yml**

Next, lets look inside of the newly created Action:

``` {.yml}
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
...
```
.github/workflows/node.js.yml

Then ```on push``` to the branch **main** all of the underneath jobs will run at the same time. Equally, if there is a ```pull request``` from any branch into main that request will run all of those jobs as well.

Next is **jobs**.

``` {.yml}
...
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
...
```
.github/workflows/node.js.yml

The build currently runs *only* on **ubuntu the latest version**. To run this in multiple operating systems, change the above as shown here:

``` {.yml}
...
jobs:
  build:

    runs-on: ${{ matrix.os}}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
...
```
.github/workflows/node.js.yml

This matrix now has three operating systems and three versions of node, so we will have (three times three is) nine jobs running.

Following are **steps**:

``` {.yml}
...
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
...
```
.github/workflows/node.js.yml



now that that bit is out of the way and we are running this in multiple versions of node multiple operating systems we can start to look into what really matters for us which is these steps over here and this first one is just to clone and check out our branch so this one is very needed right and then this one is just to set up node.js and as you can see it's already using that matrix for the node version that we are using

then is our own commands the first one is the npmci which is similar to npm installed then we are building this library we are running tests and you can run a lot of other stuff over here so for now i will just say yes start the commit i want this i will say create publish any message that you want here so any message you want here it really doesn't matter

i will say commit the new file and now i have that file over here okay and you can see that if i go now to actions it will start already a new action and this action will take anywhere from one minute to five minutes more or less so as you will see in this video i will do a lot of fast forward for you otherwise you will have to wait all the time for me and for the github actions to run okay but as you can see already you are running version 10 of node in ubuntu version 10 on
windows latest and then version 12 on both so the more operating systems and the more versions of node.js you put the more jobs will run 

if you are in a public repository is not a big deal but if you are in a private repository you have only 2 000 minutes free i think it's per month or per week i will verify input somewhere on the video uh and after that amount you will start to be charged for it so right now i will just fast forward this for you to not have to
wait for all of this to run around three minutes after as you can see over here all our jobs finish their execution
