---
title: "Introduction"
---

Fully automated release!!! semantic-release automates the whole package release workflow including: determining the next version number, generating the release notes and publishing the package.

This removes the immediate connection between human emotions and version numbers, strictly following the Semantic Versioning specification.

semantic-release is meant to be executed on the CI environment after every successful build on the release branch. This way no human is directly involved in the release process and the releases are guaranteed to be unromantic and unsentimental.

GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD. Build, test, and deploy your code right from GitHub.

Here we'll show how we can publish our packages automatically to npm every time someone does a git commit into our main branch. For that we are going to use
github actions and semantic release. If you have never heard about semantic release, it will look into all the commit messages we did since the last time we publish to npm, try to understand from all those messages what is the next version that we should publish and then go ahead and do the publish for us so
that process becomes completely automated by having github actions and semantic release.
