---
title: "Creating a GitHub repository"
---

Based on "Fully Automated npm publish using GitHub Actions and Semantic Release" at https://www.youtube.com/watch?v=QZdY4XYbqLI

Previously we have created a new ReactJS component called **foo-component**.

The **.github** directory was also created. 

Now we'll make sure we have a repository on GitHub (for convenience, but not mandatorily, named the same: **foo-component**).

We do **not** have to created a ```README.md``` or ```LICENSE``` file as these have already been created when creating the ReactJS component.

Now inside the new directory in Visual Studio Code, remove the ```.github``` directory with all content. Next, run this command:

``` {.sh}
$ git init
```

The above command will initialize a new ```.github``` directory for you.

Continue by adding all files and directories to git by typing:

``` {.sh}
$ git add .
```

And finally, run:

``` {.sh}
$ git commit -m "first commit"
$ git branch -M main
$ git remote add origin git@github.com:vanHeemstraSystems/foo-component.git
$ git push -u origin main
```

Upon inspection, you should now see all files and directories that were created as part of the ReactJS component to be in the GitHub repository at https://github.com/vanHeemstraSystems/foo-component


